server:
  port: 8899
  servlet:
    context-path: /

spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  http:
    multipart:
      enabled: true
      max-file-size: 150MB
      max-request-size: 150MB

  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    format_sql: true
  datasource-onthi:
#    driver-class-name: org.mariadb.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    jdbc-url: jdbc:mariadb://10.1.117.181:3307/s_onthi?useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: cmis1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://localhost:3306/s_onthi
    username: root
    password: 123456
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 500
      minimum-idle: 5
      pool-name: HikariPoolOnThi

logging:
  level:
    root: info
  file:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    name: logs/service-onthi.log
  logback:
    rolling-policy:
      max-history: 5
      max-file-size: 200MB

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlfArQiQt7HOVsMG0MTGqYG2aOBrWspb+nXYswA9Ft9Bqm2RslDdoz4G8KuE9cJ5ZEd6m2tI1Q1qrkVBao/9MB6+npXwtETt4V72YGB6SvlsHRBn7x2EiY5igje0mT6CiJI//AtcFIxFYv4rn7sFngDtp9N6L+DDq/c8xybsQfphgmo/mUX9pL3ei8SKODjz8wJy+9GjRH0964RpmTEG2D7zyDjit36oU0rN4Ad6UPFe6D9xdeqQDuVDJG9G6zObsPlaiVzLmaVZgYnLRkhM3LXssjwRvO6ZQRJe+r/MHt0L/+KwKzQ7EXfJG2uP+3p61bzgsMt0CxsCo7pKE6k81ywIDAQAB
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCV8CtCJC3sc5WwwbQxMapgbZo4Gtaylv6ddizAD0W30GqbZGyUN2jPgbwq4T1wnlkR3qba0jVDWquRUFqj/0wHr6elfC0RO3hXvZgYHpK+WwdEGfvHYSJjmKCN7SZPoKIkj/8C1wUjEVi/iufuwWeAO2n03ov4MOr9zzHJuxB+mGCaj+ZRf2kvd6LxIo4OPPzAnL70aNEfT3rhGmZMQbYPvPIOOK3fqhTSs3gB3pQ8V7oP3F16pAO5UMkb0brM5uw+VqJXMuZpVmBictGSEzcteyyPBG87plBEl76v8we3Qv/4rArNDsRd8kba4/7enrVvOCwy3QLGwKjukoTqTzXLAgMBAAECggEAW0Oj4Q+KkHlObReKqcL0VNuB2pKjinMUKh4rYQAqzJbkvQ8kdBdCCcSLF4KgVjNcPd9Lqrf2ybef5MSHV3lm+uq1Xao2+F09hBKYSF4brhhUVOSH97UtLHhTifAGuMMqzpyDeWQN8Wl2nqhbQl2gtVH0zaLEid6kurbqNENT5+m7PRebxEzk1NYBMPoULYB01c83zrfSn+Awbmho0wXmmx4d25bdBeaSFqv/9Vu3jGXgr88TSO7/OEzzryafp9M7RsluILvIgjiaa1g5+c3bHkyHLAQoCv0rch0BVfNhnnZjQGiOvH143WYBID3uoVIGPNGbOLPTFYura2KReEHNcQKBgQD/XmFhak1pTcP/j7mo6jTd/1KXJ5JhtDOCtnBXwg1G0GOfHJzulkVo/u3YDV8n948ISaPTFztNjW0Qy85uGdI29aIvgg/FqUhX1aMMv/pH0Tno6vlpSkaNAsoMzp4eiypJ+flhUNx6h7NDucr65s1TiN/x9M6ysglbOg0BA03PKQKBgQCWTxAdLytrt2e00SLv4uWFc8+dsjus4W+jfZEAXgWt2zmdh5sqa/eEJxvg08BbDMGt+IKDrPH5aXbXSgK0OuAq4mSLg19hUqyoIKw7r2l2Tmoo69pGjZ6JKgRzz3/SJ1qdKr4KEWoeSEDvIX0isyPhzsfXFxn5iensxmuE2Muf0wKBgQDK19QwRfkRcTUDlc2ar9aok/utl0A+HZ5g8LuR6dET88l+BINfPLwLp5uTZyOzon/ZzGy16xkvA+yjT9A8QoRpJXnblMskbc/J/SeTpBaQ30/JhIPyr44UyidmPuT4TACeXFJLi6hmJ84sOLNT0us7tFh2X8ejx6mI7jaQHGi86QKBgA3MynzzdLgaCaJ3RQ7jNRFwlZIz5/iyZe6Lu8Fd4IWayApnhd56NSpj8NJOfq2dWTbgxxLR0RGGFkwj1mW3thcZ3ANXF223CnURMt7z9unOvz5skQjDPdf4DJqZZXHk/RPK9dG00ZpgJd4OpA+IhPXZZ02fKFpZyCld+kcjJGbTAoGAP1R5oXpZwkBMiLHQukPhmjkF0H1yMMsnKX/A7M3FlLV4eUWPCMFmuCyNdKnOh7si88z5IWtsrxjVYMmZGZQC2fMMeHzevX5ynUSj1UYsfHi7KtPyYAZaAZAbxvPnOsvT8Nfx+3DYaOIeDjMXN2GvtQ0ovK5+VTwjqQ9vbE9UexM=
  secret-key: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400000
